spring.application.name=ApproveIt

spring.datasource.url=jdbc:postgresql://localhost:5432/approveit_db
spring.datasource.username=postgres
spring.datasource.password=changeme

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=change-this-secret-in-your-local-properties-file
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000